// Code generated by scenariogen from schema/cli/doctor.cue. DO NOT EDIT.
package cli

import (
	"testing"

	"github.com/galeavenworth-personal/kitty-kommander/internal/scenario"
)

// TestScenariosDoctor runs every scenario in schema/cli/doctor.cue against RunDoctor.
// Generated at build time; regenerate via `go generate ./internal/cli/`.
func TestScenariosDoctor(t *testing.T) {
	cases := []scenario.Scenario{
		{
			ID:          "doctor-drift-detected",
			Tags:        []string{"common", "doctor"},
			Story:       "A Dashboard window crashed. The operator runs doctor and\nsees drift: the Sidebar window is missing from the\nDashboard tab. The report identifies exactly what's wrong\n(which tab, which window) and suggests `kommander reload`\nas the fix. Exit code is 1 so CI wrappers can branch.",
			Invocation:  "kommander doctor",
			RunModes:    []string{"mock"},
			HelpSummary: "Drift detected:\n  kommander doctor\n  → exit 1, JSON on stdout lists missing/extra windows.\n  → stderr suggests 'kommander reload' to fix.",
			Setup: scenario.Setup{
				KittyState: &scenario.KittyFixture{
					Tabs: []scenario.KittyTab{
						{Title: "Cockpit", Windows: []scenario.KittyWindow{}},
						{Title: "Driver", Windows: []scenario.KittyWindow{
							{Title: "Driver", Cmd: scenario.StringOrList([]string{"claude"})},
						}},
						{Title: "Notebooks", Windows: []scenario.KittyWindow{
							{Title: "Notebooks", Cmd: scenario.StringOrList([]string{"euporie notebook"})},
						}},
						{Title: "Dashboard", Windows: []scenario.KittyWindow{}},
					},
				},
			},
			Expected: scenario.Expected{
				ExitCode:       1,
				StdoutContains: []string{"drift", "Sidebar", "missing"},
				StderrContains: []string{"run 'kommander reload' to reconcile"},
				JSONPaths: []scenario.JSONPath{
					{Path: ".status", Equals: "drift"},
					{Path: ".drift[0].kind", Equals: "window_missing"},
					{Path: ".drift[0].tab", Contains: "Dashboard"},
					{Path: ".drift[0].expected", Contains: "Sidebar"},
				},
			},
		},
		{
			ID:          "doctor-healthy",
			Tags:        []string{"basic", "doctor"},
			Story:       "After launching, the operator runs doctor to verify that\nthe actual kitty state matches the CUE desired state.\nAll four tabs exist with the correct windows and commands,\nso the report says healthy and exits 0.",
			Invocation:  "kommander doctor",
			RunModes:    []string{"mock"},
			HelpSummary: "Check session health:\n  kommander doctor\n  → JSON report: tab/window structure vs CUE desired state.\n  → Exit 0 healthy, exit 1 drift.",
			Setup: scenario.Setup{
				KittyState: &scenario.KittyFixture{
					Tabs: []scenario.KittyTab{
						{Title: "Cockpit", Windows: []scenario.KittyWindow{}},
						{Title: "Driver", Windows: []scenario.KittyWindow{
							{Title: "Driver", Cmd: scenario.StringOrList([]string{"claude"})},
						}},
						{Title: "Notebooks", Windows: []scenario.KittyWindow{
							{Title: "Notebooks", Cmd: scenario.StringOrList([]string{"euporie notebook"})},
						}},
						{Title: "Dashboard", Windows: []scenario.KittyWindow{
							{Title: "Sidebar", Cmd: scenario.StringOrList([]string{"kommander-ui --sidebar"})},
						}},
					},
				},
			},
			Expected: scenario.Expected{
				StdoutContains: []string{"healthy", "4/4 tabs", "0 drift"},
				JSONPaths: []scenario.JSONPath{
					{Path: ".status", Contains: "healthy"},
					{Path: ".tabs_expected", Equals: "4"},
					{Path: ".drift_count", Equals: "0"},
				},
			},
		},
		{
			ID:          "doctor-healthy-real-titles",
			Tags:        []string{"common", "doctor", "option-a-titled-layout"},
			Story:       "uib.3.C Option A contract. Production LaunchTab passes\n--title <CUE-declared title> to `kitten @ launch`; kitty\ntreats that as a persistent override that survives any\nOSC 0 escape the process emits later (claude's spinner,\neuporie's process name, bash's cwd escapes). So the state\nkitty @ ls returns post-launch carries the CUE-declared\ntitles verbatim — not the process-driven runtime strings\nintegrator observed in the pre-3.C repro (\"⠂ cell-leader\",\n\"euporie-notebook\").\n\nThis scenario asserts the full titled layout doctor must\nvalidate under Option A: Driver titled \"Driver\", Notebooks\ntitled \"Notebooks\", Dashboard/Sidebar titled \"Sidebar\",\nCockpit dynamic. The fixture deliberately declares the\ntitle on every non-dynamic window — that IS the shape a\nreal `kitten @ ls` returns after a correct launch, per the\nlive kitty probe (one-shot OSC 0 + 10Hz continuous stream\nboth failed to beat --title).\n\nRed-before-green: until schema/session/default.cue grows\n`title:` on its Driver and Notebooks windows, the desired\nside's winKey is cmd0:<token> while this fixture produces\ntitle:<Title> — they never match, drift is reported, test\nfails. The contract is what pins Option A's implementation\nin place; dropping --title from LaunchTab silently regresses\n3.F's real-kitty run while mock-path tests still pass, so\n3.F's integration scenario is what catches that direction.",
			Invocation:  "kommander doctor",
			RunModes:    []string{"mock"},
			HelpSummary: "Check session health with titled windows:\n  kommander doctor\n  → Each desired window's title matches kitty's reported\n    title (--title override survives process OSC 0 escapes).\n  → Healthy when titles + tab structure agree with CUE.",
			Setup: scenario.Setup{
				KittyState: &scenario.KittyFixture{
					Tabs: []scenario.KittyTab{
						{Title: "Cockpit", Windows: []scenario.KittyWindow{}},
						{Title: "Driver", Windows: []scenario.KittyWindow{
							{Title: "Driver", Cmd: scenario.StringOrList([]string{"claude", "--agent", "cell-leader", "--dangerously-skip-permissions"})},
						}},
						{Title: "Notebooks", Windows: []scenario.KittyWindow{
							{Title: "Notebooks", Cmd: scenario.StringOrList([]string{"euporie", "notebook"})},
						}},
						{Title: "Dashboard", Windows: []scenario.KittyWindow{
							{Title: "Sidebar", Cmd: scenario.StringOrList([]string{"kommander-ui", "--sidebar"})},
						}},
					},
				},
			},
			Expected: scenario.Expected{
				StdoutContains: []string{"healthy", "4/4 tabs", "0 drift"},
				JSONPaths: []scenario.JSONPath{
					{Path: ".status", Contains: "healthy"},
					{Path: ".tabs_expected", Equals: "4"},
					{Path: ".drift_count", Equals: "0"},
				},
			},
		},
	}
	for _, sc := range cases {
		sc := sc
		t.Run(sc.ID, func(t *testing.T) { RunScenario(t, RunDoctor, sc) })
	}
}
