// Code generated by scenariogen from schema/cli/doctor.cue. DO NOT EDIT.
package cli

import (
	"testing"

	"github.com/galeavenworth-personal/kitty-kommander/internal/scenario"
)

// TestScenariosDoctor runs every scenario in schema/cli/doctor.cue against RunDoctor.
// Generated at build time; regenerate via `go generate ./internal/cli/`.
func TestScenariosDoctor(t *testing.T) {
	cases := []scenario.Scenario{
		{
			ID:          "doctor-drift-detected",
			Tags:        []string{"common", "doctor"},
			Story:       "A Dashboard window crashed. The operator runs doctor and\nsees drift: the Sidebar window is missing from the\nDashboard tab. The report identifies exactly what's wrong\n(which tab, which window) and suggests `kommander reload`\nas the fix. Exit code is 1 so CI wrappers can branch.",
			Invocation:  "kommander doctor",
			HelpSummary: "Drift detected:\n  kommander doctor\n  → exit 1, JSON on stdout lists missing/extra windows.\n  → stderr suggests 'kommander reload' to fix.",
			Setup: scenario.Setup{
				KittyState: &scenario.KittyFixture{
					Tabs: []scenario.KittyTab{
						{Title: "Cockpit", Windows: []scenario.KittyWindow{}},
						{Title: "Driver", Windows: []scenario.KittyWindow{
							{Cmd: scenario.StringOrList([]string{"claude"})},
						}},
						{Title: "Notebooks", Windows: []scenario.KittyWindow{
							{Cmd: scenario.StringOrList([]string{"euporie notebook"})},
						}},
						{Title: "Dashboard", Windows: []scenario.KittyWindow{
							{Title: "DAG", Cmd: scenario.StringOrList([]string{"kommander-ui --dag"})},
						}},
					},
				},
			},
			Expected: scenario.Expected{
				ExitCode:       1,
				StdoutContains: []string{"drift", "Sidebar", "missing"},
				StderrContains: []string{"run 'kommander reload' to reconcile"},
				JSONPaths: []scenario.JSONPath{
					{Path: ".status", Equals: "drift"},
					{Path: ".drift[0].kind", Equals: "window_missing"},
					{Path: ".drift[0].tab", Contains: "Dashboard"},
					{Path: ".drift[0].expected", Contains: "Sidebar"},
				},
			},
		},
		{
			ID:          "doctor-healthy",
			Tags:        []string{"basic", "doctor"},
			Story:       "After launching, the operator runs doctor to verify that\nthe actual kitty state matches the CUE desired state.\nAll four tabs exist with the correct windows and commands,\nso the report says healthy and exits 0.",
			Invocation:  "kommander doctor",
			HelpSummary: "Check session health:\n  kommander doctor\n  → JSON report: tab/window structure vs CUE desired state.\n  → Exit 0 healthy, exit 1 drift.",
			Setup: scenario.Setup{
				KittyState: &scenario.KittyFixture{
					Tabs: []scenario.KittyTab{
						{Title: "Cockpit", Windows: []scenario.KittyWindow{}},
						{Title: "Driver", Windows: []scenario.KittyWindow{
							{Cmd: scenario.StringOrList([]string{"claude"})},
						}},
						{Title: "Notebooks", Windows: []scenario.KittyWindow{
							{Cmd: scenario.StringOrList([]string{"euporie notebook"})},
						}},
						{Title: "Dashboard", Windows: []scenario.KittyWindow{
							{Title: "DAG", Cmd: scenario.StringOrList([]string{"kommander-ui --dag"})},
							{Title: "Sidebar", Cmd: scenario.StringOrList([]string{"kommander-ui --sidebar"})},
						}},
					},
				},
			},
			Expected: scenario.Expected{
				StdoutContains: []string{"healthy", "4/4 tabs", "0 drift"},
				JSONPaths: []scenario.JSONPath{
					{Path: ".status", Contains: "healthy"},
					{Path: ".tabs_expected", Equals: "4"},
					{Path: ".drift_count", Equals: "0"},
				},
			},
		},
	}
	for _, sc := range cases {
		sc := sc
		t.Run(sc.ID, func(t *testing.T) { RunScenario(t, RunDoctor, sc) })
	}
}
