//go:build integration

// Code generated by scenariogen from schema/cli/integration.cue. DO NOT EDIT.
package cli

import (
	"testing"

	"github.com/galeavenworth-personal/kitty-kommander/internal/scenario"
)

// TestScenariosIntegration runs every run_modes:real_kitty scenario in schema/cli/integration.cue
// against a live kitty instance via RunIntegrationScenario.
// Generated at build time; regenerate via `go generate ./internal/cli/`.
func TestScenariosIntegration(t *testing.T) {
	cases := []scenario.Scenario{
		{
			ID:         "launch-then-doctor-clean",
			Tags:       []string{"integration", "launch", "doctor", "reload", "option-a-titled-layout"},
			Story:      "Steel-thread integration for uib.3.F. Spawn a fresh kitty on\nan isolated socket via `kommander launch`, then prove the\npost-launch state holds weight under every other subcommand\nin turn. Doctor must report healthy (0 drift) against the\nCUE-declared titled layout per Option A — proving --title\nsurvives claude's OSC 0 spinner and euporie's default\nprocess-name relabeling in a real kitty, not just in the\nmock. Reload must be a no-op — proving the auditor's\nwatchlist \"reload immediately after launch\" guard: the diff\nis empty, kitten @ ls before ≡ after, no duplicate spawns.\n\nRed-before-green at the stack level: this scenario is the\nfirst consumer of run_modes: real_kitty. Until the runner\ngrows a real-mode branch, the generated test t.Fatal's with\na specific \"real_kitty mode not implemented\" message under\n-tags=integration. The mock-path test suite (go test ./...)\nstays green — default run_modes: [\"mock\"] on every other\nscenario preserves the entire pre-3.F matrix.",
			Invocation: "",
			Steps: []scenario.Step{
				{
					Invocation: "kommander launch /tmp/kommander-integration-test",
					Expected: scenario.Expected{
						StdoutContains: []string{"session: cockpit-kommander-integration-test", "socket: unix:/tmp/kitty-kommander-kommander-integration-test"},
					},
				},
				{
					Invocation: "kommander doctor",
					Expected: scenario.Expected{
						StdoutContains: []string{"healthy", "4/4 tabs", "0 drift"},
						JSONPaths: []scenario.JSONPath{
							{Path: ".status", Contains: "healthy"},
							{Path: ".tabs_expected", Equals: "4"},
							{Path: ".drift_count", Equals: "0"},
						},
					},
				},
				{
					Invocation: "kommander reload",
					Expected: scenario.Expected{
						StdoutContains: []string{"reconciled", "0 operations"},
						KittyEffects: []scenario.KittyEffect{
							{Kind: "no_change"},
						},
					},
				},
			},
			RunModes:    []string{"real_kitty"},
			HelpSummary: "End-to-end integration flow:\n  kommander launch /path/to/project\n  kommander doctor     # healthy, 0 drift\n  kommander reload     # 0 operations (no-op on fresh session)\n  → Proves --title survives process OSC 0 escapes in a real\n    kitty and that reload is idempotent after launch.\n  → Local-only by default; `go test -tags=integration ./...`\n    spawns a real kitty. Skipped when `kitty` is not on PATH.",
			Expected: scenario.Expected{
				FinalKittyState: &scenario.KittyFixture{
					Tabs: []scenario.KittyTab{
						{Title: "Cockpit", Windows: []scenario.KittyWindow{}},
						{Title: "Driver", Windows: []scenario.KittyWindow{
							{Title: "Driver", Cmd: scenario.StringOrList([]string{"claude", "--agent", "cell-leader", "--dangerously-skip-permissions"})},
						}},
						{Title: "Notebooks", Windows: []scenario.KittyWindow{
							{Title: "Notebooks", Cmd: scenario.StringOrList([]string{"euporie", "notebook"})},
						}},
						{Title: "Dashboard", Windows: []scenario.KittyWindow{
							{Title: "Sidebar", Cmd: scenario.StringOrList([]string{"kommander-ui", "--sidebar"})},
						}},
					},
				},
			},
		},
	}
	for _, sc := range cases {
		sc := sc
		t.Run(sc.ID+"_real_kitty", func(t *testing.T) { RunIntegrationScenario(t, sc) })
	}
}
