// Package scenariogen is the CUE → Go test generator. Given the
// schema/cli/*.cue files, it emits one *_gen_test.go file per
// subcommand under internal/cli/, each containing a single
// TestScenarios<Subcmd> function with one t.Run(scenario.id, ...)
// per scenario.
//
// The generated tests construct a kitty.Mock seeded from
// scenario.setup.kitty_state, invoke the corresponding subcommand
// handler (e.g. cli.RunLaunch), and assert on the recorded
// kitty.Effects, stdout, stderr, and exit code.
//
// This file is invoked via `go generate ./internal/cli/` and is the
// only thing that writes into *_gen_test.go files. Hand editing of
// generated files is not supported — regenerate instead.
package scenariogen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/galeavenworth-personal/kitty-kommander/internal/scenario"
)

// Generate walks every loaded subcommand and writes its generated
// test file into outDir (typically internal/cli/). rootDir is the
// repo root used by scenario.Load.
func Generate(rootDir, outDir string) error {
	scs, err := scenario.Load(rootDir)
	if err != nil {
		return fmt.Errorf("load scenarios: %w", err)
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	subcmds := make([]string, 0, len(scs))
	for k := range scs {
		subcmds = append(subcmds, k)
	}
	sort.Strings(subcmds)

	for _, subcmd := range subcmds {
		// Partition scenarios by mode. A scenario with run_modes
		// containing "mock" (the default) goes into the standard
		// gen_test.go; a scenario with "real_kitty" goes into the
		// integration_gen_test.go under //go:build integration.
		// A scenario with both is emitted to both files.
		//
		// The `integration` bucket is a special case: its scenarios
		// never carry "mock" (they're real-kitty-only by design,
		// and no RunIntegration mock handler exists), so the
		// standard file is skipped entirely for that bucket.
		mockScs, realScs := partitionByMode(scs[subcmd])

		if subcmd != "integration" && len(mockScs) > 0 {
			out := filepath.Join(outDir, subcmd+"_gen_test.go")
			if err := writeTestFile(out, subcmd, mockScs); err != nil {
				return fmt.Errorf("write %s: %w", out, err)
			}
		}
		if len(realScs) > 0 {
			// Avoid the cosmetic "integration_integration_gen_test.go"
			// when the bucket IS "integration" — the suffix is already
			// implied.
			name := subcmd + "_integration_gen_test.go"
			if subcmd == "integration" {
				name = "integration_gen_test.go"
			}
			out := filepath.Join(outDir, name)
			if err := writeIntegrationTestFile(out, subcmd, realScs); err != nil {
				return fmt.Errorf("write %s: %w", out, err)
			}
		}
	}
	return nil
}

// partitionByMode splits scenarios by which mode(s) they run in.
// A scenario with RunModes containing "mock" ends up in mockScs; with
// "real_kitty" it lands in realScs; scenarios in both modes appear in
// both slices. Zero-length RunModes is normalized to ["mock"] (CUE
// default, but the loader may skip normalizing if the field was
// decoded as nil — defensive).
func partitionByMode(scs []scenario.Scenario) (mockScs, realScs []scenario.Scenario) {
	for _, s := range scs {
		modes := s.RunModes
		if len(modes) == 0 {
			modes = []string{"mock"}
		}
		for _, m := range modes {
			switch m {
			case "mock":
				mockScs = append(mockScs, s)
			case "real_kitty":
				realScs = append(realScs, s)
			}
		}
	}
	return
}

// writeIntegrationTestFile emits the real_kitty-mode test file for a
// subcommand. Carries the //go:build integration tag so `go test ./...`
// stays mock-only by default; `go test -tags=integration ./...` runs
// the real-kitty pass.
//
// Each scenario gets a t.Run(sc.ID+"_real_kitty", ...) that calls
// cli.RunIntegrationScenario(t, sc) — a single generic runner that
// dispatches per-step by invocation prefix. The integration bucket
// has no per-subcmd handler function (unlike launch/doctor/reload);
// the runner walks steps and picks handlers by the first word after
// "kommander " in each step's invocation.
func writeIntegrationTestFile(path, subcmd string, scs []scenario.Scenario) error {
	var b bytes.Buffer

	fmt.Fprintln(&b, `//go:build integration`)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// Code generated by scenariogen from schema/cli/%s.cue. DO NOT EDIT.\n", subcmd)
	fmt.Fprintln(&b, `package cli`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	"testing"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/galeavenworth-personal/kitty-kommander/internal/scenario"`)
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)

	// Test function name: avoid "IntegrationIntegration" when the
	// bucket already IS integration. Other buckets (launch,
	// doctor, reload) that opt a scenario into run_modes:real_kitty
	// get the "<Cap>Integration" suffix naturally.
	testFnBase := "TestScenarios" + strings.ToUpper(subcmd[:1]) + subcmd[1:]
	testFn := testFnBase + "Integration"
	if subcmd == "integration" {
		testFn = testFnBase
	}

	fmt.Fprintf(&b, "// %s runs every run_modes:real_kitty scenario in schema/cli/%s.cue\n", testFn, subcmd)
	fmt.Fprintf(&b, "// against a live kitty instance via RunIntegrationScenario.\n")
	fmt.Fprintf(&b, "// Generated at build time; regenerate via `go generate ./internal/cli/`.\n")
	fmt.Fprintf(&b, "func %s(t *testing.T) {\n", testFn)
	fmt.Fprintf(&b, "\tcases := []scenario.Scenario{\n")
	for _, s := range scs {
		emitScenarioLiteral(&b, s)
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tfor _, sc := range cases {\n")
	fmt.Fprintf(&b, "\t\tsc := sc\n")
	fmt.Fprintf(&b, "\t\tt.Run(sc.ID+\"_real_kitty\", func(t *testing.T) { RunIntegrationScenario(t, sc) })\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		_ = os.WriteFile(path, b.Bytes(), 0o644)
		return fmt.Errorf("gofmt: %w (wrote unformatted to %s)", err, path)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func writeTestFile(path, subcmd string, scs []scenario.Scenario) error {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by scenariogen from schema/cli/%s.cue. DO NOT EDIT.\n", subcmd)
	fmt.Fprintln(&b, `package cli`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	"testing"`)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/galeavenworth-personal/kitty-kommander/internal/scenario"`)
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)

	handler := "Run" + strings.ToUpper(subcmd[:1]) + subcmd[1:]
	testFn := "TestScenarios" + strings.ToUpper(subcmd[:1]) + subcmd[1:]

	fmt.Fprintf(&b, "// %s runs every scenario in schema/cli/%s.cue against %s.\n",
		testFn, subcmd, handler)
	fmt.Fprintf(&b, "// Generated at build time; regenerate via `go generate ./internal/cli/`.\n")
	fmt.Fprintf(&b, "func %s(t *testing.T) {\n", testFn)
	fmt.Fprintf(&b, "\tcases := []scenario.Scenario{\n")
	for _, s := range scs {
		emitScenarioLiteral(&b, s)
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tfor _, sc := range cases {\n")
	fmt.Fprintf(&b, "\t\tsc := sc\n")
	fmt.Fprintf(&b, "\t\tt.Run(sc.ID, func(t *testing.T) { RunScenario(t, %s, sc) })\n", handler)
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		// Write unformatted so the failure is debuggable.
		_ = os.WriteFile(path, b.Bytes(), 0o644)
		return fmt.Errorf("gofmt: %w (wrote unformatted to %s)", err, path)
	}
	return os.WriteFile(path, formatted, 0o644)
}

// emitScenarioLiteral writes one scenario.Scenario composite literal.
// The generator only emits fields scenarios actually use — empty
// slices and zero strings are omitted for readability of generated
// output.
func emitScenarioLiteral(b *bytes.Buffer, s scenario.Scenario) {
	fmt.Fprintf(b, "\t\t{\n")
	fmt.Fprintf(b, "\t\t\tID: %s,\n", strconv.Quote(s.ID))
	if len(s.Tags) > 0 {
		fmt.Fprintf(b, "\t\t\tTags: %s,\n", stringSliceLit(s.Tags))
	}
	if s.Story != "" {
		fmt.Fprintf(b, "\t\t\tStory: %s,\n", strconv.Quote(s.Story))
	}
	// Invocation is always emitted (even empty) so readers can
	// tell at a glance whether this is a single-invocation or
	// steps-chain scenario — empty Invocation + non-empty Steps
	// is the signal.
	fmt.Fprintf(b, "\t\t\tInvocation: %s,\n", strconv.Quote(s.Invocation))
	if len(s.Steps) > 0 {
		emitSteps(b, s.Steps)
	}
	if len(s.RunModes) > 0 {
		fmt.Fprintf(b, "\t\t\tRunModes: %s,\n", stringSliceLit(s.RunModes))
	}
	if s.HelpSummary != "" {
		fmt.Fprintf(b, "\t\t\tHelpSummary: %s,\n", strconv.Quote(s.HelpSummary))
	}
	emitSetup(b, s.Setup)
	emitExpected(b, s.Expected)
	fmt.Fprintf(b, "\t\t},\n")
}

func emitSteps(b *bytes.Buffer, steps []scenario.Step) {
	fmt.Fprintf(b, "\t\t\tSteps: []scenario.Step{\n")
	for _, st := range steps {
		fmt.Fprintf(b, "\t\t\t\t{\n")
		fmt.Fprintf(b, "\t\t\t\t\tInvocation: %s,\n", strconv.Quote(st.Invocation))
		emitStepExpected(b, st.Expected)
		fmt.Fprintf(b, "\t\t\t\t},\n")
	}
	fmt.Fprintf(b, "\t\t\t},\n")
}

// emitStepExpected is a 5-space-indent variant of emitExpected for
// Step literals. Keeping them separate (rather than parameterizing
// indent) mirrors the shape of the existing emitter, which is
// indent-coupled end-to-end; the output is readable either way.
func emitStepExpected(b *bytes.Buffer, e scenario.Expected) {
	fmt.Fprintf(b, "\t\t\t\t\tExpected: scenario.Expected{\n")
	if e.ExitCode != 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tExitCode: %d,\n", e.ExitCode)
	}
	if len(e.StdoutContains) > 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tStdoutContains: %s,\n", stringSliceLit(e.StdoutContains))
	}
	if len(e.StdoutExcludes) > 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tStdoutExcludes: %s,\n", stringSliceLit(e.StdoutExcludes))
	}
	if len(e.StderrContains) > 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tStderrContains: %s,\n", stringSliceLit(e.StderrContains))
	}
	if len(e.StderrExcludes) > 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tStderrExcludes: %s,\n", stringSliceLit(e.StderrExcludes))
	}
	if len(e.KittyEffects) > 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tKittyEffects: []scenario.KittyEffect{\n")
		for _, ef := range e.KittyEffects {
			fmt.Fprintf(b, "\t\t\t\t\t\t\t{Kind: %s", strconv.Quote(ef.Kind))
			if ef.Title != "" {
				fmt.Fprintf(b, ", Title: %s", strconv.Quote(ef.Title))
			}
			if ef.TargetTab != "" {
				fmt.Fprintf(b, ", TargetTab: %s", strconv.Quote(ef.TargetTab))
			}
			if ef.Selector != "" {
				fmt.Fprintf(b, ", Selector: %s", strconv.Quote(ef.Selector))
			}
			if ef.Text != "" {
				fmt.Fprintf(b, ", Text: %s", strconv.Quote(ef.Text))
			}
			if ef.Count > 1 {
				fmt.Fprintf(b, ", Count: %d", ef.Count)
			}
			fmt.Fprintf(b, "},\n")
		}
		fmt.Fprintf(b, "\t\t\t\t\t\t},\n")
	}
	if len(e.JSONPaths) > 0 {
		fmt.Fprintf(b, "\t\t\t\t\t\tJSONPaths: []scenario.JSONPath{\n")
		for _, jp := range e.JSONPaths {
			fmt.Fprintf(b, "\t\t\t\t\t\t\t{Path: %s", strconv.Quote(jp.Path))
			if jp.Contains != "" {
				fmt.Fprintf(b, ", Contains: %s", strconv.Quote(jp.Contains))
			}
			if jp.Equals != "" {
				fmt.Fprintf(b, ", Equals: %s", strconv.Quote(jp.Equals))
			}
			if jp.Matches != "" {
				fmt.Fprintf(b, ", Matches: %s", strconv.Quote(jp.Matches))
			}
			fmt.Fprintf(b, "},\n")
		}
		fmt.Fprintf(b, "\t\t\t\t\t\t},\n")
	}
	fmt.Fprintf(b, "\t\t\t\t\t},\n")
}

func emitSetup(b *bytes.Buffer, setup scenario.Setup) {
	if setup.KittyState == nil && len(setup.Env) == 0 && len(setup.Files) == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t\tSetup: scenario.Setup{\n")
	if len(setup.Env) > 0 {
		fmt.Fprintf(b, "\t\t\t\tEnv: %s,\n", stringMapLit(setup.Env))
	}
	if len(setup.Files) > 0 {
		fmt.Fprintf(b, "\t\t\t\tFiles: %s,\n", stringMapLit(setup.Files))
	}
	if setup.KittyState != nil {
		fmt.Fprintf(b, "\t\t\t\tKittyState: &scenario.KittyFixture{\n")
		fmt.Fprintf(b, "\t\t\t\t\tTabs: []scenario.KittyTab{\n")
		for _, tab := range setup.KittyState.Tabs {
			fmt.Fprintf(b, "\t\t\t\t\t\t{Title: %s, Windows: []scenario.KittyWindow{\n",
				strconv.Quote(tab.Title))
			for _, w := range tab.Windows {
				fmt.Fprintf(b, "\t\t\t\t\t\t\t{")
				if w.Title != "" {
					fmt.Fprintf(b, "Title: %s, ", strconv.Quote(w.Title))
				}
				fmt.Fprintf(b, "Cmd: scenario.StringOrList(%s)},\n", stringSliceLit(w.Cmd.Argv()))
			}
			fmt.Fprintf(b, "\t\t\t\t\t\t}},\n")
		}
		fmt.Fprintf(b, "\t\t\t\t\t},\n")
		fmt.Fprintf(b, "\t\t\t\t},\n")
	}
	fmt.Fprintf(b, "\t\t\t},\n")
}

func emitExpected(b *bytes.Buffer, e scenario.Expected) {
	fmt.Fprintf(b, "\t\t\tExpected: scenario.Expected{\n")
	if e.ExitCode != 0 {
		fmt.Fprintf(b, "\t\t\t\tExitCode: %d,\n", e.ExitCode)
	}
	if len(e.StdoutContains) > 0 {
		fmt.Fprintf(b, "\t\t\t\tStdoutContains: %s,\n", stringSliceLit(e.StdoutContains))
	}
	if len(e.StdoutExcludes) > 0 {
		fmt.Fprintf(b, "\t\t\t\tStdoutExcludes: %s,\n", stringSliceLit(e.StdoutExcludes))
	}
	if len(e.StderrContains) > 0 {
		fmt.Fprintf(b, "\t\t\t\tStderrContains: %s,\n", stringSliceLit(e.StderrContains))
	}
	if len(e.StderrExcludes) > 0 {
		fmt.Fprintf(b, "\t\t\t\tStderrExcludes: %s,\n", stringSliceLit(e.StderrExcludes))
	}
	if len(e.KittyEffects) > 0 {
		fmt.Fprintf(b, "\t\t\t\tKittyEffects: []scenario.KittyEffect{\n")
		for _, ef := range e.KittyEffects {
			fmt.Fprintf(b, "\t\t\t\t\t{Kind: %s", strconv.Quote(ef.Kind))
			if ef.Title != "" {
				fmt.Fprintf(b, ", Title: %s", strconv.Quote(ef.Title))
			}
			if ef.TargetTab != "" {
				fmt.Fprintf(b, ", TargetTab: %s", strconv.Quote(ef.TargetTab))
			}
			if ef.Selector != "" {
				fmt.Fprintf(b, ", Selector: %s", strconv.Quote(ef.Selector))
			}
			if ef.Text != "" {
				fmt.Fprintf(b, ", Text: %s", strconv.Quote(ef.Text))
			}
			if ef.Count > 1 {
				fmt.Fprintf(b, ", Count: %d", ef.Count)
			}
			fmt.Fprintf(b, "},\n")
		}
		fmt.Fprintf(b, "\t\t\t\t},\n")
	}
	if e.KittyEffectsExact {
		fmt.Fprintf(b, "\t\t\t\tKittyEffectsExact: true,\n")
	}
	if len(e.JSONPaths) > 0 {
		fmt.Fprintf(b, "\t\t\t\tJSONPaths: []scenario.JSONPath{\n")
		for _, jp := range e.JSONPaths {
			fmt.Fprintf(b, "\t\t\t\t\t{Path: %s", strconv.Quote(jp.Path))
			if jp.Contains != "" {
				fmt.Fprintf(b, ", Contains: %s", strconv.Quote(jp.Contains))
			}
			if jp.Equals != "" {
				fmt.Fprintf(b, ", Equals: %s", strconv.Quote(jp.Equals))
			}
			if jp.Matches != "" {
				fmt.Fprintf(b, ", Matches: %s", strconv.Quote(jp.Matches))
			}
			fmt.Fprintf(b, "},\n")
		}
		fmt.Fprintf(b, "\t\t\t\t},\n")
	}
	if e.FinalKittyState != nil {
		fmt.Fprintf(b, "\t\t\t\tFinalKittyState: &scenario.KittyFixture{\n")
		fmt.Fprintf(b, "\t\t\t\t\tTabs: []scenario.KittyTab{\n")
		for _, tab := range e.FinalKittyState.Tabs {
			fmt.Fprintf(b, "\t\t\t\t\t\t{Title: %s, Windows: []scenario.KittyWindow{\n",
				strconv.Quote(tab.Title))
			for _, w := range tab.Windows {
				fmt.Fprintf(b, "\t\t\t\t\t\t\t{")
				if w.Title != "" {
					fmt.Fprintf(b, "Title: %s, ", strconv.Quote(w.Title))
				}
				fmt.Fprintf(b, "Cmd: scenario.StringOrList(%s)},\n", stringSliceLit(w.Cmd.Argv()))
			}
			fmt.Fprintf(b, "\t\t\t\t\t\t}},\n")
		}
		fmt.Fprintf(b, "\t\t\t\t\t},\n")
		fmt.Fprintf(b, "\t\t\t\t},\n")
	}
	fmt.Fprintf(b, "\t\t\t},\n")
}

func stringSliceLit(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(s))
	}
	b.WriteString("}")
	return b.String()
}

func stringMapLit(m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("map[string]string{")
	for i, k := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%s: %s", strconv.Quote(k), strconv.Quote(m[k]))
	}
	b.WriteString("}")
	return b.String()
}
